namespace NodeJS {
  interface ProcessEnv {

    /**
     *
     * URL generated by Vercel Preview Deployment
     * Triggered by any code push on any branch within repo.
     *
     * Used in baseURL attribute of `playwright.config.ts` 
     * to determine endpoint for running E2E Tests.
     * @type {string}
     */
    PLAYWRIGHT_TEST_BASE_URL: string
  }
}
