// import { type Database } from "@/db/drizzle";
// import { app_feedback } from "@/db/drizzle/schema";
// import { TRPCError } from "@trpc/server";

// Hint: Look at createAnnouncementPost from 
// "src/server/dao/announcements.ts"

// Goal: Create "DAO" (Database Access Object) (rather method...) in order
// to create a record within the database using drizzle
//
// This method should accept the following parameters:
// * db: Database
// * feedback_name: string
// * feedback_report: string
//
// The other parameters we created in our schema are automatically generated
// * feedback_id: auto-incrementing serial integer
// * feedback_timestamp: generated by SQL when record is created
//
// Use auto-complete to your own advantage, as the LSP should help you.
